name:
on:
  pull_request:
    branch: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: use NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: lts/-1
       - run: npm ci
       - run: npm test -- --coverage
         env:
           CI: true

